In [1]:
!pip install nltk

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import Counter
from torch.utils.data import Dataset,DataLoader
from nltk.tokenize import word_tokenize


In [3]:
document = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""


In [4]:
import nltk

In [5]:
nltk.download('punkt')
nltk.download('punkt_tab')


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\anjal\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\anjal\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [6]:
tokens = word_tokenize(document.lower())

In [7]:
vocab = {'<UNK>':0}
for token in Counter(tokens).keys():
    if token not in vocab:
        vocab[token] = len(vocab)

vocab


{'<UNK>': 0,
 'about': 1,
 'the': 2,
 'program': 3,
 'what': 4,
 'is': 5,
 'course': 6,
 'fee': 7,
 'for': 8,
 'data': 9,
 'science': 10,
 'mentorship': 11,
 '(': 12,
 'dsmp': 13,
 '2023': 14,
 ')': 15,
 'follows': 16,
 'a': 17,
 'monthly': 18,
 'subscription': 19,
 'model': 20,
 'where': 21,
 'you': 22,
 'have': 23,
 'to': 24,
 'make': 25,
 'payments': 26,
 'of': 27,
 'rs': 28,
 '799/month': 29,
 '.': 30,
 'total': 31,
 'duration': 32,
 '?': 33,
 '7': 34,
 'months': 35,
 'so': 36,
 'becomes': 37,
 '799': 38,
 '*': 39,
 '=': 40,
 '5600': 41,
 'approx': 42,
 'syllabus': 43,
 'we': 44,
 'will': 45,
 'be': 46,
 'covering': 47,
 'following': 48,
 'modules': 49,
 ':': 50,
 'python': 51,
 'fundamentals': 52,
 'libraries': 53,
 'analysis': 54,
 'sql': 55,
 'maths': 56,
 'machine': 57,
 'learning': 58,
 'ml': 59,
 'algorithms': 60,
 'practical': 61,
 'mlops': 62,
 'case': 63,
 'studies': 64,
 'can': 65,
 'check': 66,
 'detailed': 67,
 'here': 68,
 '-': 69,
 'https': 70,
 '//learnwith.campusx.i

In [8]:
len(vocab)

289

In [9]:
input_sentences = document.split('\n')


In [10]:
input_sentences

['About the Program',
 'What is the course fee for  Data Science Mentorship Program (DSMP 2023)',
 'The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.',
 'What is the total duration of the course?',
 'The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)',
 'What is the syllabus of the mentorship program?',
 'We will be covering the following modules:',
 'Python Fundamentals',
 'Python libraries for Data Science',
 'Data Analysis',
 'SQL for Data Science',
 'Maths for Machine Learning',
 'ML Algorithms',
 'Practical ML',
 'MLOPs',
 'Case studies',
 'You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390',
 'Will Deep Learning and NLP be a part of this program?',
 'No, NLP and Deep Learning both are not a part of this program’s curriculum.',
 'What if I miss a live session? Will I get a recording 

In [11]:
def text_to_indices(sentence,voccab):
    numerical_sentence = []

    for token in sentence:

        if token in vocab:
            numerical_sentence.append(vocab[token])

        else:
            numerical_sentence.append(vocab['<UNK>'])

    return numerical_sentence

In [12]:
input_numerical_sentences = []

for sentence in input_sentences:
    input_numerical_sentences.append(text_to_indices(word_tokenize(sentence.lower()),vocab))

In [13]:
len(input_numerical_sentences)

78

In [14]:
training_Sequence = []

for sentence in input_numerical_sentences:

    for i in range(1,len(sentence)):
        training_Sequence.append(sentence[:i+1])
    

In [15]:
training_Sequence[:5]

[[1, 2], [1, 2, 3], [4, 5], [4, 5, 2], [4, 5, 2, 6]]

In [16]:
len_list = []
for seq in training_Sequence:
    len_list.append(len(seq))

max(len_list)

62

In [17]:
padded_training_seq = []
for seq in training_Sequence:
    padded_training_seq.append([0]*(max(len_list)-len(seq)) + seq)

In [18]:
len(padded_training_seq[0])

62

In [19]:
padded_training_seq = torch.tensor(padded_training_seq,dtype=torch.long)

In [20]:
padded_training_seq

tensor([[  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        [  0,   0,   0,  ...,   0,   4,   5],
        ...,
        [  0,   0,   0,  ..., 285, 176, 286],
        [  0,   0,   0,  ..., 176, 286, 287],
        [  0,   0,   0,  ..., 286, 287, 288]])

In [21]:
X = padded_training_seq[:,:-1]
y = padded_training_seq[:,-1]

In [22]:
X

tensor([[  0,   0,   0,  ...,   0,   0,   1],
        [  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   0,   0,   4],
        ...,
        [  0,   0,   0,  ...,   0, 285, 176],
        [  0,   0,   0,  ..., 285, 176, 286],
        [  0,   0,   0,  ..., 176, 286, 287]])

In [23]:
y

tensor([  2,   3,   5,   2,   6,   7,   8,   9,  10,  11,   3,  12,  13,  14,
         15,   6,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  18,  26,
         27,  28,  29,  30,   5,   2,  31,  32,  27,   2,   6,  33,  31,  32,
         27,   2,   6,   5,  34,  35,  30,  36,   2,  31,   6,   7,  37,  38,
         39,  34,  40,  28,  41,  12,  42,  30,  15,   5,   2,  43,  27,   2,
         11,   3,  33,  45,  46,  47,   2,  48,  49,  50,  52,  53,   8,   9,
         10,  54,   8,   9,  10,   8,  57,  58,  60,  59,  64,  65,  66,   2,
         67,  43,  68,  69,  70,  50,  71,  72,  58,  73,  74,  46,  17,  75,
         27,  76,   3,  33,  78,  74,  73,  72,  58,  79,  80,  81,  17,  75,
         27,  76,   3,  82,  83,  84,  30,  85,  86,  87,  17,  88,  89,  33,
         45,  86,  90,  17,  91,  27,   2,  89,  33,  93,  94,  95,  80,  96,
         78,  36,  97,  85,  22,  87,  17,  89,  22,  65,  98,  99,  73, 100,
          2,  91,  30,  65,  86, 101,   2, 102, 103,  33,  76, 1

In [24]:
class Custom_dataset(Dataset):

    def __init__(self,X,y):
        self.X = X
        self.y = y

    def __len__(self):
        return self.X.shape[0]
    
    def __getitem__(self, index):
        return self.X[index],self.y[index]

In [25]:
dataset = Custom_dataset(X,y)


In [26]:
len(dataset)

942

In [27]:
datasloader = DataLoader(dataset,batch_size=32,shuffle=True)

In [28]:
for ip,op in datasloader:
    print(ip,op)

tensor([[  0,   0,   0,  ...,  93, 151,  18],
        [  0,   0,   0,  ..., 201,   2, 149],
        [  0,   0,   0,  ...,  68,   5,   2],
        ...,
        [  0,   0,   0,  ...,  30,   4, 263],
        [  0,   0,   0,  ...,   2, 149,  30],
        [  0,   0,   0,  ..., 186,  78,  22]]) tensor([ 26,  30, 177,  93, 151,  46, 154, 242, 131, 144,  86, 154, 146,  27,
         30, 126,  97,  82, 179, 246,  93,  95,  94,   6,  33,   6, 156, 149,
        112, 264,  36,  45])
tensor([[  0,   0,   0,  ..., 227,  73,  22],
        [  0,   0,   0,  ...,   2, 175,  78],
        [  0,   0,   0,  ...,   2,   6,   5],
        ...,
        [  0,   0,   0,  ..., 112,  33, 113],
        [  0,   0,   0,  ..., 177,  24, 179],
        [  0,   0,   0,  ...,   0,   4,  85]]) tensor([ 23,   4,  34,  30, 133, 163,  27, 164,  86,  33, 139,  23, 166,  70,
        100, 157,   2,  28,  25, 126, 240,  30, 183, 226, 118, 151,  30,   2,
         93,  30,   7,  86])
tensor([[  0,   0,   0,  ..., 185, 186,  78],
    

In [51]:
class LSTM_Model(nn.Module):

    def __init__(self,vocab_size):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size,100)
        self.lstm = nn.LSTM(100,150,batch_first=True)
        self.fc = nn.Linear(150,vocab_size)

    def forward(self,x):
        embedded = self.embedding(x)
        intermediate_hidden_states,(final_hidden_state,final_cell_state) = self.lstm(embedded)
        output = self.fc(final_hidden_state).squeeze(0)
        return output
        

In [52]:
model = LSTM_Model(len(vocab))

In [53]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

Using device: cuda


In [54]:
model.to(device)

LSTM_Model(
  (embedding): Embedding(289, 100)
  (lstm): LSTM(100, 150, batch_first=True)
  (fc): Linear(in_features=150, out_features=289, bias=True)
)

In [55]:
epochs = 50
learning_rate = 0.001

loss_fun = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters(),lr=learning_rate)

In [56]:
for epoch in range(epochs):

    total_loss = 0

    for batch_x,batch_y in datasloader:
        batch_x ,batch_y = batch_x.to(device),batch_y.to(device)

        optimizer.zero_grad()

        y_pred = model(batch_x)

        loss = loss_fun(y_pred,batch_y)

        loss.backward()

        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch: {epoch+1},Loss: {total_loss:.4f}")
    

Epoch: 1,Loss: 166.1598
Epoch: 2,Loss: 146.0200
Epoch: 3,Loss: 133.3082
Epoch: 4,Loss: 121.2872
Epoch: 5,Loss: 109.3977
Epoch: 6,Loss: 97.9300
Epoch: 7,Loss: 87.3454
Epoch: 8,Loss: 77.3524
Epoch: 9,Loss: 68.4862
Epoch: 10,Loss: 60.2013
Epoch: 11,Loss: 53.3314
Epoch: 12,Loss: 46.5636
Epoch: 13,Loss: 41.1909
Epoch: 14,Loss: 35.9234
Epoch: 15,Loss: 31.8219
Epoch: 16,Loss: 27.5866
Epoch: 17,Loss: 24.3308
Epoch: 18,Loss: 21.5392
Epoch: 19,Loss: 19.1379
Epoch: 20,Loss: 17.0825
Epoch: 21,Loss: 15.4092
Epoch: 22,Loss: 13.9840
Epoch: 23,Loss: 12.6624
Epoch: 24,Loss: 11.6478
Epoch: 25,Loss: 10.8035
Epoch: 26,Loss: 10.0410
Epoch: 27,Loss: 9.2770
Epoch: 28,Loss: 8.9411
Epoch: 29,Loss: 8.2275
Epoch: 30,Loss: 7.7928
Epoch: 31,Loss: 7.4425
Epoch: 32,Loss: 7.1924
Epoch: 33,Loss: 7.1393
Epoch: 34,Loss: 6.6124
Epoch: 35,Loss: 6.4172
Epoch: 36,Loss: 6.0563
Epoch: 37,Loss: 5.8670
Epoch: 38,Loss: 5.7173
Epoch: 39,Loss: 5.4331
Epoch: 40,Loss: 5.3782
Epoch: 41,Loss: 5.3033
Epoch: 42,Loss: 5.2291
Epoch: 43,Lo

In [59]:
def prediction(model,vocab,text):
    
    #tokenize
    tokenized_text = word_tokenize(text.lower())

    #text to indices
    numerical_text = text_to_indices(tokenized_text,vocab)

    #padding
    padded_text = torch.tensor([0]*(61-len(numerical_text)) + numerical_text,dtype=torch.long).unsqueeze(0).to(device)

    output = model(padded_text)

    value,index = torch.max(output,dim=1)

    return text + " " + list(vocab.keys())[index]

In [60]:
prediction(model,vocab,"total duration of")

'total duration of the'

In [62]:
import time


num_tokens = 10
input_text = "total duration of"

for i in range(num_tokens):
    output_text = prediction(model,vocab,input_text)
    print(output_text)
    input_text = output_text
    time.sleep(0.5)

total duration of the
total duration of the course
total duration of the course is
total duration of the course is 7
total duration of the course is 7 months
total duration of the course is 7 months .
total duration of the course is 7 months . so
total duration of the course is 7 months . so the
total duration of the course is 7 months . so the total
total duration of the course is 7 months . so the total course
