In [1]:
import torch

## Creating a tensor


In [2]:
#using empty - it allocates memory and dont assign value to that space and the values that were already there are displayed

a =torch.empty(2,3)

In [3]:
#check type

type(a)

torch.Tensor

In [4]:
#using zeroes

torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
#using ones

torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
#using rand

torch.rand(2,3)

tensor([[0.8788, 0.1686, 0.3768],
        [0.7788, 0.2112, 0.6598]])

In [7]:
#manual_seed

torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [8]:
# using tensor

torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
# arange

print("using arange ->",torch.arange(0,10,2))  # (start,end,stop)

#linspace

print("using linspace ->",torch.linspace(0,10,10)) # evenly spaced between a range and how much

#eye

print("using eye ->",torch.eye(5)) #identity matrix

#full

print("using full ->",torch.full((3,3),5)) #dim,what's the value

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor shapes


In [10]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
x.shape

torch.Size([2, 3])

In [12]:
#to create a tensor of same shape

torch.empty_like(x) #shape of which tensor - x

tensor([[0, 0, 0],
        [0, 0, 0]])

In [13]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [14]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [15]:
torch.rand_like(x,dtype =torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [16]:
x.dtype

torch.int64

In [17]:
#assign data type

torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [18]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [19]:
# using to() -> changing data type of existing tensor

x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## Mathematical Operations 

#### 1. Scalar operation


In [20]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [21]:
#addition
print(x + 2)

# subtraction
print(x - 2)
#multiplication
print(x * 2)

#division
print(x / 3)
 
#int division
print((x * 100) // 3)

#mod
print(((x * 100) // 3) % 2)

#power
print(x**2)

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])
tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])
tensor([[1.4235, 1.5752],
        [0.8366, 1.8028]])
tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])
tensor([[23., 26.],
        [13., 30.]])
tensor([[1., 0.],
        [1., 0.]])
tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])


#### 2. Element Wise Operation

In [22]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [23]:
#add 
a+b

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [24]:
#sub 
a-b

tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])

In [25]:
#mul
a*b

tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])

In [26]:
#div
a/b

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])

In [27]:
#power
a**b

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])

In [28]:
#mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [29]:
c = torch.tensor([1,-2,3,-4])

In [30]:
#abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [31]:
#negative

torch.neg(c)

tensor([-1,  2, -3,  4])

In [32]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [33]:
#round
torch.round(d)

tensor([2., 2., 4., 4.])

In [34]:
#ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [35]:
#floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [36]:
#clamp -> keep numbers in a range

torch.clamp(d,min=2,max=3)


tensor([2.0000, 2.3000, 3.0000, 3.0000])

#### 3.Reduction operation

reduce whole tensor to a single tensor


In [37]:
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [38]:
#sum
torch.sum(e)

tensor(24.)

In [39]:
#sum along columns

torch.sum(e,dim=0)

tensor([ 8.,  0., 16.])

In [40]:
#sum along rows

torch.sum(e,dim=1)

tensor([15.,  9.])

In [41]:
#mean
torch.mean(e)

tensor(4.)

In [42]:
#mean along col

torch.mean(e,dim=0)

tensor([4., 0., 8.])

In [43]:
#median

torch.median(e)

tensor(0.)

In [44]:
#max and min
torch.max(e)

tensor(9.)

In [45]:
torch.min(e)

tensor(0.)

In [46]:
#product
torch.prod(e)

tensor(0.)

In [47]:
#st. deviation

torch.std(e)

tensor(4.4272)

In [48]:
#variance

torch.var(e)

tensor(19.6000)

In [49]:
#argmax -> position of largest element

torch.argmax(e)

tensor(5)

In [50]:
#argmin -> postion of smallest element

torch.argmin(e)

tensor(1)

#### 3. Matrix operation

In [51]:
f = torch.randint(size=(2,3),low=0,high=10)
g = torch.randint(size=(3,2),low=0,high=10)

print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [52]:
# matrix mul
torch.matmul(f,g)

tensor([[ 87, 119],
        [ 65,  99]])

In [53]:
#dot product

vec1 = torch.tensor([1,2])
vec2 = torch.tensor([3,4])

torch.dot(vec1,vec2)


tensor(11)

In [54]:
#transpose

torch.transpose(f,0,1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [55]:
h =  torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[5., 9., 8.],
        [9., 7., 9.],
        [2., 6., 7.]])

In [56]:
#determint

torch.det(h)

tensor(-110.)

In [57]:
#inverse

torch.inverse(h)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

#### 5. Comparison operations

In [58]:
i = torch.randint(size=(2,3),low=0,high=10)
j = torch.randint(size = (2,3),low=0,high=10)

print(i)
print(j)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0, 4],
        [3, 8, 8]])


In [59]:
#greater than
i > j

tensor([[ True,  True, False],
        [ True, False, False]])

In [60]:
# less than

i< j

tensor([[False, False,  True],
        [False,  True,  True]])

In [61]:
#equal to

i==j

tensor([[False, False, False],
        [False, False, False]])

In [62]:
#not equal to 
i!=j

tensor([[True, True, True],
        [True, True, True]])

In [63]:
#greater than equal to
i>=j

tensor([[ True,  True, False],
        [ True, False, False]])

In [64]:
#lesser than equal to
i<=j

tensor([[False, False,  True],
        [False,  True,  True]])

#### 6. Special functions

In [65]:
k = torch.randint(size=(2,3),low=0,high=10,dtype = torch.float32)
k

tensor([[3., 3., 5.],
        [0., 6., 4.]])

In [66]:
#log

torch.log(k)

tensor([[1.0986, 1.0986, 1.6094],
        [  -inf, 1.7918, 1.3863]])

In [67]:
#exponents

torch.exp(k)

tensor([[ 20.0855,  20.0855, 148.4132],
        [  1.0000, 403.4288,  54.5981]])

In [68]:
# sqrt

torch.sqrt(k)

tensor([[1.7321, 1.7321, 2.2361],
        [0.0000, 2.4495, 2.0000]])

In [69]:
# sigmoid

torch.sigmoid(k)

tensor([[0.9526, 0.9526, 0.9933],
        [0.5000, 0.9975, 0.9820]])

In [70]:
#softmax

torch.softmax(k,dim=0)

tensor([[0.9526, 0.0474, 0.7311],
        [0.0474, 0.9526, 0.2689]])

In [71]:
# relu
torch.relu(k)

tensor([[3., 3., 5.],
        [0., 6., 4.]])

## Inplace operations

In [72]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])
tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [73]:
m.add_(n)  # _ represent inplace opr

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [74]:
m


tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [75]:
torch.relu(m)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [76]:
m.relu_()

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [77]:
m


tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

## Copying a tensor

In [78]:
a = torch.rand(2,3)
a

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [79]:
b = a

In [80]:
b

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [81]:
a[0][0] = 0

In [82]:
a

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [83]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [84]:
id(a)

1901352870560

In [85]:
id(b)

1901352870560

a and b both are referring to same memory location because of assignment opr
b is not a new tensor

In [86]:
b = a.clone()

In [87]:
a

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [88]:
a[0][0]=10

In [89]:
a

tensor([[10.0000,  0.2324,  0.9141],
        [ 0.7668,  0.1659,  0.4393]])

In [90]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [91]:
print(id(a))
print(id(b))

1901352870560
1901352664128


## Tensor operations on GPU

In [92]:
torch.cuda.is_available()

True

In [93]:
device = torch.device('cuda')

In [94]:
# creating new tensor on gpu

torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [95]:
# moving an existing cpu tensor on gpu
a


tensor([[10.0000,  0.2324,  0.9141],
        [ 0.7668,  0.1659,  0.4393]])

In [96]:
c = a.to(device)
c

tensor([[10.0000,  0.2324,  0.9141],
        [ 0.7668,  0.1659,  0.4393]], device='cuda:0')

In [97]:
c + 5

tensor([[15.0000,  5.2324,  5.9141],
        [ 5.7668,  5.1659,  5.4393]], device='cuda:0')

In [98]:
import time 

size =10000

#CPU

matrix_cpu1 = torch.rand(size,size)
matrix_cpu2 = torch.rand(size,size)

start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1,matrix_cpu2)
cpu_time = time.time() - start_time

print(f"Time on cpu: {cpu_time:.4f} seconds")

#GPU

matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# Warm up GPU
for _ in range(3):
    _ = torch.matmul(matrix_gpu1, matrix_gpu2)
torch.cuda.synchronize()

start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1,matrix_gpu2)
torch.cuda.synchronize()
gpu_time = time.time() - start_time

print(f"Time on gpu: {gpu_time:.4f} seconds")

#compare results

print("\nSpeedup (CPU time/GPU time):",cpu_time/gpu_time)

Time on cpu: 3.8263 seconds
Time on gpu: 0.4436 seconds

Speedup (CPU time/GPU time): 8.62482372642341


## Reshaping tensors

In [99]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [100]:
#reshape 
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [101]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [102]:
b = torch.rand(2,3,4)
b

tensor([[[0.3932, 0.7483, 0.7985, 0.4626],
         [0.9414, 0.5752, 0.8881, 0.7989],
         [0.9514, 0.0141, 0.8903, 0.1649]],

        [[0.3162, 0.1331, 0.6763, 0.4254],
         [0.2375, 0.5430, 0.1174, 0.6532],
         [0.5115, 0.3094, 0.7907, 0.7351]]])

In [103]:
#permute

b.permute(2,0,1).shape


torch.Size([4, 2, 3])

In [104]:
# unsqueeze

c = torch.rand(226,226,3)
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [105]:
# squeeze

d = torch.rand(1,20)

d.squeeze(0).shape

torch.Size([20])

## NumPy and PyTorch

In [106]:
import numpy as np


In [107]:
#pytorch tensor to numpy array

a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [108]:
b = a.numpy()

In [109]:
b

array([1, 2, 3])

In [110]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [111]:
#numpy array to tensor
torch.from_numpy(c)

tensor([1, 2, 3])