In [13]:
import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self,num_features):

        super().__init__()
        self.linear1 = nn.Linear(num_features,3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self,features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out
    
    

In [14]:
features = torch.rand(10,5)

model = Model(features.shape[1])
model(features)

tensor([[0.3800],
        [0.4000],
        [0.3788],
        [0.4220],
        [0.4220],
        [0.4164],
        [0.4106],
        [0.3937],
        [0.4205],
        [0.3915]], grad_fn=<SigmoidBackward0>)

In [17]:
model.linear2.weight

Parameter containing:
tensor([[-0.3259, -0.3043, -0.3611]], requires_grad=True)

In [ ]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [18]:
class Model1(nn.Module):

    def __init__(self,num_features):

        super().__init__()
        self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid(),
        )

    def forward(self,features):
        out = self.network(features)
        return out
    

In [19]:
model1 = Model1(features.shape[1])
model1(features)

tensor([[0.3878],
        [0.3788],
        [0.3804],
        [0.3799],
        [0.4042],
        [0.3773],
        [0.3795],
        [0.3850],
        [0.4023],
        [0.3817]], grad_fn=<SigmoidBackward0>)